# Model Configs
model:
  lr: 0.0001 # learning rate
  use_lr_scheduler: False # if you want to use learning rate scheduler
  train_batch_size: 4
  test_batch_size: 8
  train_epochs: 100
  model_output_path: "../results/checkpoints/epoch_{}.pt"
  load_saved_model: False # if you want pre-trained model weights to be loaded
  model_input_path: "output/model/pems08/epoch_58_model.pt" # pretrained model path
  log_file: "../results/app.log" # pretrained model path
  device: cuda # decides GPU or CPU for training
  graph_weight_encoder:
    dim_model: 64 # dimension that embedding layer maps the input of the model to.
    seq_len: 21 # input sequence length
    input_dim: 9 # input dimension, inputs is traffic flow value, in some dataset it may be combined with time index
    num_layers: 4 # # of temporal encoder layers
    num_heads: 8 # # of temporal encoder layers
    dropout_e_normal: 0.0 # dropout applied to the final output of temporal encoder layer of the first encoder
    dropout_e_rep: 0.2 # dropout applied to the final output of temporal encoder layer of the second encoder (representative time sequence)
  temporal_encoder:
    dim_model: 64 # dimension that embedding layer maps the input of the model to.
    seq_len: 21 # input sequence length
    input_dim: 9 # input dimension, inputs is traffic flow value, in some dataset it may be combined with time index
    num_layers: 4 # # of temporal encoder layers
    num_heads: 8 # # of temporal encoder layers
    dropout_e_normal: 0.0 # dropout applied to the final output of temporal encoder layer of the first encoder
    dropout_e_rep: 0.2 # dropout applied to the final output of temporal encoder layer of the second encoder (representative time sequence)
  gat:
    ogm_input_dim: 2
    dim_model: 32
    dim_cell_model: 16
    dim_adj_model: 32
    dim_edge: 1
    num_heads: 4
    dropout: 0.2
  unet:
    ogm_input_dim: 2
    dim_model: 16
    dim_edge: 1
    num_heads: 4
    dropout: 0.2
    img_ch: 4
    output_ch: 4

# Data Configs
data:
  dataset_dir: "../data/"
  label_dir: "../data/annotations/"
  dataset: "ind" # dataset name
  visualizer_params_dir: "../data/visualizer_params/"
  history_length: 20
  num_features: 9 # number of features of the input data
  num_workers: 1 # number of workers for data loading